[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "currex"
version = "0.1.0"
description = "A Pythonic currency calculator with real-time exchange rates"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Piotr Migdał" },
]
dependencies = [
    "requests>=2.31.0",
    "pytest>=7.4.0",
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/stared/currex"

[tool.hatch.build.targets.wheel]
packages = ["currex"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
markers = [
    "api: marks tests that require external API access (deselect with '-m \"not api\"')",
] 